steps:
  - trigger: "dummy-repo-b"
    label: "🔗 Trigger Repo B build"
    build:
      message: "${BUILDKITE_MESSAGE}"
      commit: "${BUILDKITE_COMMIT}"
      branch: "${BUILDKITE_BRANCH}"
      env:
        UPSTREAM_PULL_REQUEST: "${BUILDKITE_PULL_REQUEST}"
        UPSTREAM_PULL_REQUEST_BASE_BRANCH: "${BUILDKITE_PULL_REQUEST_BASE_BRANCH}"
        UPSTREAM_PULL_REQUEST_REPO: "${BUILDKITE_PULL_REQUEST_REPO}"
